name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: dutterbutter/foundry-zksync-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build 
        id: build

      - name: Run Era Test Node
        uses: dutterbutter/era-test-node-action@db/update-for-evm-usage
        with:
          mode: 'fork'
          showCalls: 'user'
          showStorageLogs: 'read'
          showVmDetails: 'all'
          showGasDetails: 'all'
          resolveHashes: 'true'
          debugMode: 'true'
          devSystemContracts: 'local'
          emulateEvm: 'true'
          log: 'info'
          logFilePath: 'era_test_node.log'
          target: 'x86_64-unknown-linux-gnu'
          releaseTag: 'latest'

      - name: Test deploy
        run: |
          forge script script/NFT.s.sol:MyScript --rpc-url=http://127.0.0.1:8011 -g 50000